server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3306
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1


